### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by ishanivardhan** [NHSLeadership/moodle-theme_nightingale#10]
Login & Forgot password page just needs a visit to see how existing Nightingale elements & components can be used to style the page

cc: @cehwitham

**Comment by ishanivardhan** [comment]
@Pro-Paul - I'm going to change the status to "Blocked" and remove myself from the Assignee. 
Please update the designs as per our today's discussion & once you have it finalised in Abstract, change the status to 'Available' & assignee to myself for me to pick this up then.

**Comment by penpadstudio** [comment]
Login mobile and Tablet/Desktop designs are ready for feedback (please leave any comments on the abstract branch): https://share.goabstract.com/c8985cb2-48e4-46f7-bb5b-3705f0fdee89

**Comment by ishanivardhan** [comment]
Due to more control over core login templates in our theme folder, the login page has got most of the styling bits of Nightingale as is with very few minor aesthetic pieces undone such as red border around input boxes in case of error & little crosses 'x' at the end of input fields. 

This is due to our limited usage of JS and some bits of functionality sitting in core needed to modify this. (Can be pursued with more time in next versions, if required.)

There is a small cookie ribbon issue which re-appears even after being dismissed as it doesn't remember the user preference. Will pursue that in a separate ticket that deals with Cookie Ribbon.
 
Raising a PR for this!

**Comment by cehwitham** [comment]
@Android63 can you show @ishanivardhan how you implemented HTML5 offline content for the cookie bar in WordPress please?
