### ISSUE TITLE
User Profile Individual page

### ISSUE THREAD

**Issue by ishanivardhan** [NHSLeadership/moodle-theme_nightingale#13]
The each individual user profile page, the URL for which looks like this on my local http://localhost/staging_dev/user/profile.php?id=23

This page can be found from clicking "Profile" from Top Nav OR clicking on any User from User list site wide.

cc: @cehwitham

**Comment by Pro-Paul** [comment]
This was not an agreed feature to be released in v1 from our original meeting.

**Comment by ishanivardhan** [comment]
@Pro-Paul - It's the page when you click on User Profile button. Admins use it when they want to log in as some one and Participants themselves use it when required. 

The meeting may not have discussed all the possible pages but if this page is a result of something the user gets on clicking the components we are designing as part of v1.0.0 (For instance the header profile button), then I'm not sure how it would look when they come to a non-styled page?

@cehwitham thoughts?

**Comment by penpadstudio** [comment]
For those in confusion. I deleted my previous comment that the issue was created after the v1 milestone creations. @cehwitham  has stated that this will be added into v.1.

**Comment by cehwitham** [comment]
@ishanivardhan I think this probably falls under some of the default styling we were talking about. Once we've got the basic content/sidebar column setup and default typography in place, I think a lot of these pages will start to look pretty reasonable.

**Comment by ishanivardhan** [comment]
@cehwitham - I think we have now come to a point where we have the 2-column layout/sidebar sorted and based on recent discussions wrt design, it would still be best if @Pro-Paul can nip a quick design to piece together what's already there under User Profile in Moodle and skin it using Nightingale scheme of things.

Changing Status to "Blocked" & Assignee to @Pro-Paul to do this.

**Comment by ishanivardhan** [comment]
@Pro-Paul - I see this design for User Profile page in Abstract. Is this correct?

![User-Profile-Design](https://user-images.githubusercontent.com/25176815/33072980-56960cea-ceb9-11e7-983d-1168ca26842b.png)

If yes, then this is not exactly in line with existing Moodle User profile page and doesn't have all the elements that we need styling to complete this page. 

Existing Moodle profile page
![Moodle profile page](https://user-images.githubusercontent.com/25176815/33073209-0cb6ebfc-ceba-11e7-9a05-1972883a7f42.png)

If you could take a look again & fix this design to match more with existing Moodle page please, that would be great!

cc: @cehwitham

**Comment by ishanivardhan** [comment]
@Pro-Paul - any update on this?

**Comment by ishanivardhan** [comment]
Since @Pro-Paul is on leave and we didn't have an updated design for User Profile page & related pages, have simply styled them using Nightingale structure.

Tried to spend a bit of time modifying the layout of the page so the structure could look different than default Moodle. But since all code sits in core lib file `lib/myprofilelib.php`, any attempts to make a copy of it failed and hence retained default layout but styling with Nightingale.

Raising a PR for this.
