### ISSUE TITLE
Moodle Messages

### ISSUE THREAD

**Issue by ishanivardhan** [NHSLeadership/moodle-theme_nightingale#15]
Issue to decide whether or not to include Message in Profile Sub Nav. 

If yes, then need to discuss design & user-experience aspects and things like do we show indication of new/unread Messages with a number (in red) on top & should that Messages menu item open as a sub-nav in itself or simply be a clickable link to take to a new page?

cc: @cehwitham

**Comment by penpadstudio** [comment]
@ishanivardhan @cehwitham Can this issue be closed and re-opened after v1.0?

**Comment by ishanivardhan** [comment]
Yes @Pro-Paul - It depends on the extent of usage of this feature. Closing it now. Lets re-open later with more details if work needs to be done on it.
