### ISSUE TITLE
Implement Nightingale header and navigation in Moodle

### ISSUE THREAD

**Issue by ishanivardhan** [NHSLeadership/moodle-theme_nightingale#3]
The header and navigation needs to be made Nightingale based in Moodle. Some major layout and template restructuring might be required.

**Comment by ishanivardhan** [comment]
@Pro-Paul , @cehwitham - Can we keep Header & Navigation as one of the top priority items as well since Paul had done some designs & I had already started working on it? Would be good to finish & close that.

**Comment by cehwitham** [comment]
This is technically above the others as it is "Doing" not "ToDo"?

**Comment by ishanivardhan** [comment]
Yes just thought will bring it up for both of you, especially @Pro-Paul so he can modify designs as per our latest discussions & finalise them in Abstract!

**Comment by ishanivardhan** [comment]
@cehwitham - Not sure if we need to get Harry to build the blue header from Paul's designs made in Abstract. Also there is no such button type as the "profile" one that I could find in latest Nightingale styles?

**Comment by ishanivardhan** [comment]
@cehwitham - Normal participants or non admins would see "Contact" as one of the menu items instead of "Site Admin". Any thoughts on where this link should go to? External site?
(Just so I know, what href value would go in)

**Comment by cehwitham** [comment]
>Any thoughts on where this link should go to? External site?
(Just so I know, what href value would go in)

Probably a question for @TobiasReece

**Comment by penpadstudio** [comment]
I would suggest external link to corp site for now, or a support contact page. Ideally we could have a page replicated from the external site internally on Moodle so not to unnecessarily re-direct the user, but its debateable.

**Comment by TobiasReece** [comment]
I think the contact page should just be a brief info page with support number and email. I agree with Paul that this shouldn't unnecessarily re-direct the user. Also, if its on Seacole (for eg) we should see a separate email address to Anderson (for eg)

**Comment by ishanivardhan** [comment]
1. Most of the Header is done. Navigation dropdown links are all dynamic with access to all courses. When clicked on any Course, it would either ask for Enrolment key or show the Listing page if already enrolled.

2. An additional setting **Contact page URL** is added that's configurable from the Theme backend. It can contain Moodle or external page link

3. Button, alignment styles are tweaked, not perfect; Will pick them from [Moodle Header](https://github.com/NHSLeadership/nightingale/issues/117) ticket once ready.

Header for admin looks like - 
![screen shot 2017-08-23 at 18 19 34](https://user-images.githubusercontent.com/25176815/29629421-a4a06e8c-8830-11e7-8a82-91d897c9a950.png)

Header for non-admin (student) looks like -
![screen shot 2017-08-23 at 18 20 35](https://user-images.githubusercontent.com/25176815/29629428-b12a0a00-8830-11e7-8123-f3616e1834b9.png)
