### ISSUE TITLE
Profile in Header Nav

### ISSUE THREAD

**Issue by ishanivardhan** [NHSLeadership/moodle-theme_nightingale#6]
The "Profile" nav item would be a button in Moodle's header which when opened would act as sub-nav to show only list items. It also may have red dot on it based on unread Messages inside it. 
What would it look like when "Messages", an item under Profile which in itself can act as a min sub-nav is undecided until we have more designs from @Pro-Paul 

Desktop design for Profile so far:
![screen shot 2017-08-11 at 15 07 34](https://user-images.githubusercontent.com/25176815/29216510-d3e9cf82-7ea6-11e7-9957-0ec6f8971cac.png)

Mobile design for Profile:
![screen shot 2017-08-11 at 15 09 01](https://user-images.githubusercontent.com/25176815/29216662-4858a456-7ea7-11e7-872a-c945be118413.png)

cc: @cehwitham

**Comment by ishanivardhan** [comment]
We have made it so the sub-nav under Profile no longer exists and it's a button instead which when clicked takes to the Profile page which pretty much has all the links that used to be under sub-nav.

Log Out was the only button/link not present which is made as a nav button next to Profile button.

All this being pursued as part of [tkt-00003](https://github.com/NHSLeadership/moodle-theme_nightingale/issues/3)

**Comment by cehwitham** [comment]
If this is a duplicate @ishanivardhan can we remove priority.

Status: Won't Fix / Type: Duplicate.
