### ISSUE TITLE
Moodle Dashboard

### ISSUE THREAD

**Issue by ishanivardhan** [NHSLeadership/moodle-theme_nightingale#7]
Need to decide what Dashboard page should look like. Moodle has two pages

- Home
Intro text & Images, listing of Available courses & Site news (if Any)

- Dashboard
User specific showing courses that he / she enrolled in; Course related student activity etc.

We can look at examples from SeaLoc VC, Vanilla Moodle 3.3 & Anderson/Bevan to see what existing Home page/Dashboard looks like to decide on a simplistic design.

cc: @cehwitham

**Comment by penpadstudio** [comment]
https://share.goabstract.com/f04025b9-3fb3-40e9-8207-7b9ee57b073a

Dashboard designed, will discuss further with @ishanivardhan.

**Comment by ishanivardhan** [comment]
I think it would be advisable to have @TobiasReece or @adamref or even yourself @cehwitham  give us some screenshots of what items a Dashboard can or should particularly contain so @Pro-Paul 's design can cover more of those elements and we don't miss out on core Moodle functionality.

(Ex: If we check Essex VC and login as one of the participants to view their Dashboard it show us the pending Journal entries, pending Turnitin Assignments, etc which is not in the current design but can be useful if we give @Pro-Paul some screenshots with different elements of Dashboard)

**Comment by ishanivardhan** [comment]
As per discussions with @Pro-Paul & @cehwitham - keeping impending research with use of Dashboard by participants & Facilitators in mind we are simply skinning the existing Dashboard page with Nightingale designs rather than completely changing it.

**Comment by ishanivardhan** [comment]
As per our discussions from Oct 2 (above comment), have mostly retained Moodle layout but with Nightingale styling for now

Due to Moodle’s core template not having course background image for course cards in Dashboard area & having a progress wheel instead of a bar — I have styled it accordingly without changing the layout for v1.0 atleast.

Will pursue any pending tasks for Dashboard with modified designs in [separate ticket](https://github.com/NHSLeadership/moodle-theme_nightingale/issues/49)

Raising a PR for this one @cehwitham
